from . import res_config_settings
from . import res_partner
from . import hr_applicant
from . import hr_contract_type
from . import hr_education_level
from . import hr_activity
from . import hr_channel
from . import hr_metier
from . import hr_job
